export const GET_OFFRES_BY_CAT_BEGIN='GET_OFFRES_BY_CAT_BEGIN'
export const GET_OFFRES_BY_CAT_SUCCESS='GET_OFFRES_BY_CAT_SUCCESS'
export const GET_OFFRES_BY_CAT_FAIL='GET_OFFRES_BY_CAT_FAIL'
export const GET_OFFRES_BY_ID_BEGIN='GET_OFFRES_BY_ID_BEGIN'
export const GET_OFFRES_BY_ID_SUCCESS='GET_OFFRES_BY_ID_SUCCESS'
export const GET_OFFRES_BY_ID_FAIL='GET_OFFRES_BY_ID_FAIL'

export const POSTULER_OFFRES_BEGIN='POSTULER_OFFRES_BEGIN'
export const POSTULER_OFFRES_SUCCESS='POSTULER_OFFRES_SUCCESS'
export const POSTULER_OFFRES_FAIL='POSTULER_OFFRES_FAIL'

export const GET_MY_OFFRES_BEGIN='GET_MY_OFFRES_BEGIN'
export const GET_MY_OFFRES_SUCCESS='GET_MY_OFFRES_SUCCESS'
export const GET_MY_OFFRES_FAIL='GET_MY_OFFRES_FAIL'
